using Microsoft.AspNetCore.Mvc;
using NileconTest.Models;
using System.Diagnostics;
using System.Net.Mime;

namespace NileconTest.Services
{
    public class ContentService
    {
        private List<ContentModel> _db;

        public ContentService()
        {
            _db = new List<ContentModel>
            {
                new ContentModel() { contentID = 1, contentTitle = "ฮาย อาภาพร – ธัช กิตติธัช สุดอึ้ง!!!  เพลงไทยร้องยากแต่ชาวต่างชาติร้องได้", contentImage = "https://site-assets.mediaoxide.com/workpointtv/2024/09/11114048/1K0A6569_0.jpg", contentDescription = "พุธนี้ เตรียมความสนุกสุดเซอร์ไพรส์ของ 3 ชาติหัวใจไทย ที่ต้องมาร้องเพลงไทยแข่งกัน!!! นำโดย “คุณมินท์” สาวน้อยสุดสดใสจากประเทศสิงคโปร์ ชื่นชมประเทศไทยเพราะสามารถทำให้ฝันด้านวงการบันเทิงของเธอเป็นจริงได้ ต้องเจอกับวิศวะกรเครื่องจักรกลจากประเทศเยอรมนี “คุณโนบี้” เวลามาที่ไทยรู้สึกอบอุ่นมากๆทุกครั้ง และชอบมารยาทของคนไทย การไหว้ เพลงไทย เพราะมันทำให้ยิ่งหลงรักประเทศไทยยิ่งขึ้น และคนสุดท้าย “คุณวิล” หนุ่มหล่อสุดเท่จากอังกฤษ อยากอยู่ประเทศไทยให้นานที่สุด อยากพูดภาษาไทยให้คล่องๆ และเข้าใจวัฒนธรรมไทยให้มากขึ้น เพราะอยู่ที่ไทยให้ความรู้สึกเหมือนอยู่บ้าน" },
                new ContentModel() { contentID = 2, contentTitle = "“หมอลำไอดอล ซีซั่น 2” เปิดเวทีความม่วนครบทุกอารมณ์ เริ่มวันศุกร์ที่ 13 ก.ย.นี้ เวลา 6 โมงเย็น ทางช่องเวิร์คพอยท์ 23", contentImage = "https://site-assets.mediaoxide.com/workpointtv/2024/09/10152231/%E0%B8%AB%E0%B8%A1%E0%B8%AD%E0%B8%A5%E0%B8%B3%E0%B9%84%E0%B8%AD%E0%B8%94%E0%B8%AD%E0%B8%A5-%E0%B8%8B%E0%B8%B5%E0%B8%8B%E0%B8%B1%E0%B9%88%E0%B8%99-2-4.jpg", contentDescription = "เตรียมเปิดหน้าจอรับความม่วน พร้อมกันทั่วทุกพื้นที่ ในรายการ “หมอลำไอดอล ซีซั่น 2” ออกอากาศ ทุกวันศุกร์ เวลา 6 โมงเย็น และวันเสาร์ เวลา 15.45 น. เริ่มเปิดฤดูกาลวันแรกในวันศุกร์ที่ 13 กันยายน ทางช่องเวิร์คพอยท์ 23" },
                new ContentModel() { contentID = 3, contentTitle = "เปิดรับสมัครแล้ว  “Genwit อัจฉริยะพันธุ์ใหม่ Presented by Bangchak Group ซีซั่น 2”", contentImage = "https://site-assets.mediaoxide.com/workpointtv/2024/09/10151652/%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%AA%E0%B8%A1%E0%B8%B1%E0%B8%84%E0%B8%A3-ss2-1.jpg", contentDescription = "อัจฉริยะพันธุ์ใหม่อาจะเป็นคุณ! ซีซั่น 2 เริ่มเปิดรับสมัครทีมโรงเรียนระดับมัธยมปลายเพื่อร่วมแข่งขันชิงถ้วยพระราชทานสมเด็จพระกนิษฐาธิราชเจ้า กรมสมเด็จพระเทพรัตนราชสุดาฯ และทุนการศึกษาจากกลุ่มบริษัทบางจากแล้ววันนี้" },
                new ContentModel() { contentID = 4, contentTitle = "“R U RALLY 2″  “แอนนาเสือ VS แอนชิลี”  ฮามงลง ลุยภารกิจสุดท้าทาย", contentImage = "https://site-assets.mediaoxide.com/workpointtv/2024/09/06143119/R-U-RALLY-%E0%B9%81%E0%B8%AD%E0%B8%99%E0%B8%99%E0%B8%B2-vs-%E0%B9%81%E0%B8%AD%E0%B8%99%E0%B8%8A%E0%B8%B4%E0%B8%A5%E0%B8%B5-1_0-scaled.jpg", contentDescription = "Content Description: สนุกสนานกันทุกวันอาทิตย์ ในรายการ “R U RALLY 2” (อาร์ยูแรลลี่สอง) กับภารกิจสุดท้าทายระหว่างทีมเรด และทีมแบล็ค ซึ่งอาทิตย์นี้ เป็นการมาเจอกันของแขกรับเชิญสาวสวยมงลง 2 นางงามมากกว่าสามารถ “แอนนา เสืองามเอี่ยม VS แอนชิลี สก็อต-เคมมิส” โดยจะพาไปตะลุยกรุงเทพมหานครแบบสุดมัน ทำเอาต่างทุ่มสุดตัวแบบใจเกินร้อย ไม่ว่าจะเป็นเกมที่ต้องใส่รองเท้าส้นสูงเกินบนกระดาษไปทั้งทีม เกมปาโป่งวัดความแม่นยำ และความไวในการพลิกกล่อง สองสาวสองแอนทำไปได้เต็มที่สุดๆ ขนาด 4 พิธีกรอย่าง “เจแปน ภาณุพรรณ คารีสา สปริงเก็ตต์ ไนกี้ นิธิดล และปิงปอง ธงชัย” ถึงกับเอ่ยปากชมว่าเล่นได้สุดเต็มที่ไม่มีห่วงสวย"},
                new ContentModel() { contentID = 5, contentTitle = "ค่าย  “Newgen Entertainment”  จัดเต็มความเศร้าระดับจักรวาลปล่อยเพลง “เสี่ยงแชทอ้ายไว้ไส” จับคู่ “นนท์ อชิร – แอนนาเสือ” ถ่ายทอดความรู้สึกของคนรอ", contentImage = "https://site-assets.mediaoxide.com/workpointtv/2024/09/05112355/Screenshot-2024-09-05-112322.png", contentDescription = "ถือว่าได้รับการตอบรับอย่างล้นหลามและความฮือฮา เพียงแค่ปล่อย Teaser เพลง “เสี่ยงแชทอ้ายไว้ไส” ซิงเกิ้ลใหม่ล่าสุดจากค่าย “Newgen Entertainment” (นิวเจน เอ็นเตอร์เทนเมนท์) เพื่อเอาใจคอเพลงเศร้า ของหนุ่มหล่อเสียงดี “นนท์ อชิร” ศิลปินจากเวทีหมอลำไอดอล ได้เพียงไม่กี่วัน จนเป็นกระแสในโลกโซเชียล" },
                new ContentModel() { contentID = 6, contentTitle = "3 หนุ่มต่างสไตล์!!! อาร์ม กรกันต์ – แจ็ค แฟนฉัน – โบนัส ณัฐวัฒน์ สุดประทับใจร่วมตัดสินชาวต่างชาติร้องเพลงไทย!!!", contentImage = "https://site-assets.mediaoxide.com/workpointtv/2024/09/04110910/1K0A9401_0.jpg", contentDescription = "ยังคงเป็นกระแสต่อเนื่องสำหรับรายการ “โอ้ละหนอ I Love เมืองไทย” รายการวาไรตี้เกมโชว์ที่เปิดโอกาสให้ “นานาชาติ” มาจับไมค์แข่งขันร้องเพลงไทย ที่สร้างความภาคภูมิใจให้คนไทย ที่ได้เห็นชาวต่างชาติรักเมืองไทย เพลงไทย วัฒนธรรมไทย ได้มากขนาดนี้ ออกอากาศทุกวันพุธ เวลา 20.15 น. ทางช่องเวิร์คพอยท์ 23 ซึ่งผ่านมาหลายสัปดาห์แล้วแต่ความประทับใจยังไม่มีจางหาย ยังคงทวีความสุขและความปลื้มใจที่ได้เห็นชาวต่างชาติมาถ่ายทอดบทเพลงไทยจากหัวใจให้พวกเราคนไทยได้ฟัง" },
                new ContentModel() { contentID = 7, contentTitle = "ช่องเวิร์คพอยท์ 23 x โคตรคูล ส่ง “ละคร KOOL น่ะทำ” ยกความฮามาทั้งจักรวาล  เริ่มวันพุธที่ 4 กันยายน นี้ เวลา 21.30 น. ทางช่องเวิร์คพอยท์ 23", contentImage = "https://site-assets.mediaoxide.com/workpointtv/2024/09/03120238/%E0%B8%A5%E0%B8%B0%E0%B8%84%E0%B8%A3-KOOL-%E0%B8%99%E0%B9%88%E0%B8%B0%E0%B8%97%E0%B8%B3-%E0%B9%80%E0%B8%A3%E0%B8%B4%E0%B9%88%E0%B8%A1%E0%B8%A7%E0%B8%B1%E0%B8%99%E0%B8%9E%E0%B8%B8%E0%B8%98%E0%B8%97%E0%B8%B5%E0%B9%88-4-%E0%B8%81.%E0%B8%A2-9.jpg", contentDescription = "ช่องเวิร์คพอยท์ 23 ร่วมกับ บริษัท โคตรคูล ส่งซิตคอมสุดฮา “ละคร KOOL น่ะทำ” ทุกวันพุธ เริ่มออกอากาศตอนแรก วันพุธที่ 4 กันยายนนี้ เวลา 21.30 น. ทางช่องเวิร์คพอยท์ 23" },
                new ContentModel() { contentID = 8, contentTitle = "“R U RALLY 2″  “ตุ๊กกี้ สุดารัตน์ VS เก้า จิรายุ”  ยกทีมฮาพาตะลุยกรุงเทพมหานคร", contentImage = "https://site-assets.mediaoxide.com/workpointtv/2024/08/29145827/R-URALLY-%E0%B8%95%E0%B8%B8%E0%B9%8A%E0%B8%81%E0%B8%81%E0%B8%B5%E0%B9%89-vs-%E0%B9%80%E0%B8%81%E0%B9%89%E0%B8%B2-2_0.jpg", contentDescription = "วันอาทิตย์นี้ รายการ “R U RALLY 2″ (อาร์ยูแรลลี่สอง) สนุกสุดฮากันต่อเนื่องกับสองแขกรับเชิญพี่น้องคู่ซี้ “ตุ๊กกี้ สุดารัตน์ และ เก้า จิรายุ” ที่จะพาทุกคนยกทีมฮาตะลุยภารกิจสุดมันกันที่กรุงเทพมหานคร เรียกว่าท้าแดด ท้าลม และท้าฝน ก็ทุ่มกันสุดตัว พร้อม 4 พิธีกรสายลุยอย่าง “เจแปน ภาณุพรรณ, คารีสา สปริงเก็ตต์, ไนกี้ นิธิดล และปิงปอง ธงชัย”" },
                new ContentModel() { contentID = 9, contentTitle = "ARTISTS LINE UP  “PEPSI Presents T-POP Concert Fest 3” เปิดจำหน่ายบัตร Early Bird Early Bird: 1,000 บาท วันที่ 30 ส.ค. เวลา 18.00 น. – 2 ก.ย. 67", contentImage = "https://site-assets.mediaoxide.com/workpointtv/2024/08/28112910/457255218_470575109133115_3117152421895459000_ncc.jpg", contentDescription = "“PEPSI Presents T-POP Concert Fest 3” กลับมาอีกครั้ง! เทศกาลดนตรี T-POP ขนาดใหญ่ใจกลางเมือง บัตรคอนเสิร์ตที่คุ้มที่สุด และรวมเหล่าศิลปิน TPOP เอาไว้อย่างมากมาย" },
                new ContentModel() { contentID = 10, contentTitle = "ศิลปินคุณภาพ ตั้ม – โดม – โย่ง รวมพลังตัดสินต่างชาติร้องเพลงไทย", contentImage = "https://site-assets.mediaoxide.com/workpointtv/2024/08/27150759/1K0A4091_0.jpg", contentDescription = "เรียกได้ว่าเป็นปรากฏการณ์ความภาคภูมิใจของคนไทยไม่หยุดจริง ๆ สำหรับ รายการ “โอ้ละหนอ I Love เมืองไทย” รายการวาไรตี้เกมโชว์ที่เปิดโอกาสให้ “นานาชาติ” มาจับไมค์แข่งขันร้องเพลงไทย ออกอากาศทุกวันพุธ เวลา 20.15 น. ทางช่องเวิร์คพอยท์ 23 ซึ่งเป็นสัปดาห์ที่ 6 แล้ว แต่ความประทับใจยังไม่มีจางหาย ยังคงทวีคูณความสนุกขึ้นเรื่อย ๆ เพราะยังมีชาวต่างชาติ ที่หลงรักเมืองไทยอีกมากมาย มาร่วมถ่ายทอดบทเพลงไทยจากหัวใจให้ผู้ชมได้ฟังกันและภูมิใจแบบต่อเนื่อง" },
                new ContentModel() { contentID = 11, contentTitle = "“R U RALLY 2″  ฮาท้าคลื่นทะเล  “ตั้ม วราวุธ VS โดม จารุวัฒน์” ลุยภารกิจ จ.ชลบุรี", contentImage = "https://site-assets.mediaoxide.com/workpointtv/2024/08/22143059/R-U-RALLY2-%E0%B8%8A%E0%B8%A5%E0%B8%9A%E0%B8%B8%E0%B8%A3%E0%B8%B5-%E0%B8%95%E0%B8%B1%E0%B9%89%E0%B8%A1-%E0%B9%82%E0%B8%94%E0%B8%A1-6_0.png", contentDescription = "วันอาทิตย์นี้ ฮาท้าคลื่นทะเลกับ 2 หนุ่มเสียงดีเพื่อนซี้สุดป่วน “ตั้ม วราวุธ VS โดม จารุวัฒน์” พาตะลุยภารกิจที่จังหวัดชลบุรี ใน รายการ “R U RALLY 2″ (อาร์ยูแรลลี่สอง) ออกเดินทางสุดมันไปพร้อม 4 พิธีกรสายฮา “เจแปน ภาณุพรรณ, คารีสา สปริงเก็ตต์, ไนกี้ นิธิดล และปิงปอง ธงชัย”"},
                new ContentModel() { contentID = 12, contentTitle = "“ชิงช้าสวรรค์ 2025”  เปิดรับสมัคร วงดนตรีลูกทุ่งระดับมัธยมศึกษาทั่วประเทศ", contentImage = "https://site-assets.mediaoxide.com/workpointtv/2024/08/21152124/Screenshot-2024-08-21-152104.png", contentDescription = "วันอาทิตย์นี้ ฮาท้าคลื่นทะเลกับ 2 หนุ่มเสียงดีเพื่อนซี้สุดป่วน “ตั้ม วราวุธ VS โดม จารุวัฒน์” พาตะลุยภารกิจที่จังหวัดชลบุรี ใน รายการ “R U RALLY 2″ (อาร์ยูแรลลี่สอง) ออกเดินทางสุดมันไปพร้อม 4 พิธีกรสายฮา “เจแปน ภาณุพรรณ, คารีสา สปริงเก็ตต์, ไนกี้ นิธิดล และปิงปอง ธงชัย”"}
            };
        }

        public List<ContentModel> getAllContent() => _db;
        public ContentModel getContentByID(int id) => _db.Find(c => c.contentID == id);
        public void addContent(ContentModel contentData) => _db.Add(contentData);
        public void updateContent(int id, ContentModel newObj)
        {
            var content = _db.Find(c => c.contentID == id);
            if (content != null)
            {
                content.contentTitle = newObj.contentTitle;
                content.contentImage = newObj.contentImage;
                content.contentDescription = newObj.contentDescription;
            }
        }
        public void removeContent(ContentModel obj) => _db.Remove(obj);
    }
}